Challenge1
sambiase/desafios_java pull request #1
Opened 2022-08-02 14:29 UTC by sambiase

new request

2022-08-02 14:48 UTC, jcralmeida requested changes

2022-08-02 14:48 UTC, jcralmeida commented on pom.xml
> +
Dependencies go after the properties

2022-08-02 14:48 UTC, jcralmeida commented on src/main/java/readCSV.java
> +    public static void main(String[] args) {
Let's create a new file called Main, add move the main method to it

2022-08-02 14:48 UTC, jcralmeida commented on src/main/java/readCSV.java
> +    static final String WRITE_FILE ="/home/sambiase/JavaProjects/desafios_java/desafios_java/src/main/java/times.csv";
Let's receive this values as program arguemnts

2022-08-02 14:48 UTC, jcralmeida commented on src/main/java/readCSV.java
> +    static final String WRITE_FILE ="/home/sambiase/JavaProjects/desafios_java/desafios_java/src/main/java/times.csv";
Also this values should be obtained via Main method that you should create

2022-08-02 14:48 UTC, jcralmeida commented on src/main/java/readCSV.java
> +            CSVParser csvRead = new CSVParser(new FileReader(READ_FILE),CSVFormat.DEFAULT.withHeader("id","first_name","last_name"));
Not a good practice to hard-coded the schema

2022-08-02 14:48 UTC, jcralmeida commented on src/main/java/readCSV.java
> +public class readCSV {
Let's change this name since it does not only read csv but it writes too

2022-08-03 12:55 UTC, sambiase commented on src/main/java/readCSV.java
> +    public static void main(String[] args) {
Done

2022-08-03 12:56 UTC, sambiase commented on src/main/java/readCSV.java
> +    static final String WRITE_FILE ="/home/sambiase/JavaProjects/desafios_java/desafios_java/src/main/java/times.csv";
Implemented as requested

2022-08-03 12:56 UTC, sambiase commented on src/main/java/readCSV.java
> +            CSVParser csvRead = new CSVParser(new FileReader(READ_FILE),CSVFormat.DEFAULT.withHeader("id","first_name","last_name"));
resolved

2022-08-03 12:56 UTC, closed without merging